import os

Import('zipbld')

contents = []
content = 'core.js browserOverlay.xul mailOverlay.xul options.xul options.js songOverlay.xul icon.png icon.svg'
for c in content.split(' '):
    contents.append('content' + os.sep + c)

locales = 'en-US it-IT ru-RU pl-PL pt-BR ja-JP fr-FR de-DE sk-SK zh-CN'
locale_files = 'browserOverlay.dtd core.properties mailOverlay.dtd options.dtd'
 
for l in locales.split(' '):
   for f in locale_files.split(' '): 
      contents.append('locale' + os.sep + l + os.sep + f)

env = Environment(ZIPCHDIR= 'chrome', BUILDERS = {'Zip' : zipbld})
r = env.Zip('#dist/chrome/firetray.jar', contents)

Return('r')
