import os

Import('zipbld')

contents = []
content = 'core.js browserOverlay.xul mailOverlay.xul options.xul'
for c in content.split(' '):
    contents.append('content' + os.sep + c)
# ru-RU pl-PL pt-BR ja-JP
locales = 'en-US it-IT'
locale_files = 'browserOverlay.dtd core.properties mailOverlay.dtd options.dtd'
 
for l in locales.split(' '):
   for f in locale_files.split(' '): 
      contents.append('locale' + os.sep + l + os.sep + f)

env = Environment(ZIPCHDIR= 'chrome', BUILDERS = {'Zip' : zipbld})
r = env.Zip('#dist/chrome/firetray.jar', contents)

Return('r')
