#include "nsISupports.idl"

interface nsIBaseWindow;
 
[scriptable, uuid(bf249f85-20f2-49be-96f3-9681f3bb0334)]
interface nsITray : nsISupports
{
    void showTray();
    void hideTray();
	void minimize(in PRUint32 aCount, [array, size_is(aCount)] in nsIBaseWindow aBaseWindows);
	void restore(); 
};
